export const C = {
  bg: '#F7F6F2',
  surface: '#FFFFFF',
  border: '#E8E4DC',
  borderStrong: '#D4CEC2',
  ink: '#1a1a1a',
  inkMute: '#5b5751',
  inkFaint: '#8a857c',
  fake: '#C0392B',
  real: '#27AE60',
  amber: '#E67E22',
  fakeTint: 'rgba(192, 57, 43, 0.10)',
  fakeTintStrong: 'rgba(192, 57, 43, 0.18)',
  realTint: 'rgba(39, 174, 96, 0.10)',
  amberTint: 'rgba(230, 126, 34, 0.10)',
  blueTint: 'rgba(40, 80, 140, 0.09)',
  rowAlt: '#FBFAF6',
};

export const SERIF = "Georgia, 'Times New Roman', Times, serif";
export const SANS  = "system-ui, -apple-system, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif";
export const MONO  = "ui-monospace, SFMono-Regular, Menlo, Consolas, 'Liberation Mono', monospace";

export const S = {
  page: {
    minHeight: '100vh',
    background: C.bg,
    color: C.ink,
    fontFamily: SERIF,
  },
  shell: {
    maxWidth: 1120,
    margin: '0 auto',
    padding: '0 32px',
  },
  nav: {
    borderBottom: `1px solid ${C.border}`,
    background: C.bg,
  },
  navInner: {
    maxWidth: 1120,
    margin: '0 auto',
    padding: '18px 32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logo: {
    display: 'flex',
    alignItems: 'baseline',
    gap: 10,
    textDecoration: 'none',
    color: C.ink,
    cursor: 'pointer',
  },
  logoMark: {
    width: 26, height: 26,
    background: C.ink,
    color: '#fff',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: SERIF,
    fontSize: 16,
    fontWeight: 700,
    transform: 'translateY(4px)',
  },
  logoWord: {
    fontFamily: SERIF,
    fontSize: 22,
    letterSpacing: '-0.01em',
  },
  logoSub: {
    fontFamily: SANS,
    fontSize: 11,
    letterSpacing: '0.14em',
    textTransform: 'uppercase',
    color: C.inkMute,
    marginLeft: 2,
  },
  navLinks: {
    display: 'flex',
    gap: 28,
    fontFamily: SANS,
    fontSize: 13,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
  },
  navLink: (active) => ({
    color: active ? C.ink : C.inkMute,
    textDecoration: 'none',
    paddingBottom: 4,
    borderBottom: active ? `1.5px solid ${C.ink}` : '1.5px solid transparent',
    cursor: 'pointer',
  }),
  hero: {
    padding: '56px 0 28px',
    borderBottom: `1px solid ${C.border}`,
  },
  heroTitle: {
    fontFamily: SERIF,
    fontSize: 64,
    lineHeight: 1.02,
    letterSpacing: '-0.025em',
    fontWeight: 400,
    margin: 0,
    color: C.ink,
  },
  heroSub: {
    fontFamily: SANS,
    fontSize: 14,
    color: C.inkMute,
    marginTop: 18,
    maxWidth: 560,
    lineHeight: 1.55,
  },
  tabs: {
    display: 'flex',
    gap: 32,
    borderBottom: `1px solid ${C.border}`,
    paddingTop: 28,
    fontFamily: SANS,
    fontSize: 13,
    letterSpacing: '0.04em',
    overflowX: 'auto',
  },
  tab: (active) => ({
    padding: '10px 0 14px',
    background: 'transparent',
    border: 'none',
    borderBottom: active ? `2px solid ${C.ink}` : '2px solid transparent',
    color: active ? C.ink : C.inkMute,
    fontWeight: active ? 600 : 400,
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    marginBottom: -1,
  }),
  twoCol: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.45fr) minmax(0, 1fr)',
    gap: 24,
    padding: '32px 0 80px',
  },
  card: {
    background: C.surface,
    border: `1px solid ${C.border}`,
    padding: 24,
  },
  cardHead: {
    fontFamily: SANS,
    fontSize: 11,
    letterSpacing: '0.16em',
    textTransform: 'uppercase',
    color: C.inkFaint,
    marginBottom: 14,
  },
  textarea: {
    width: '100%',
    minHeight: 280,
    border: 'none',
    background: 'transparent',
    resize: 'vertical',
    fontFamily: SERIF,
    fontSize: 18,
    lineHeight: 1.55,
    color: C.ink,
    padding: 0,
  },
  inputRow: {
    display: 'flex',
    alignItems: 'center',
    borderBottom: `1px solid ${C.border}`,
    padding: '6px 0 10px',
    gap: 12,
  },
  urlInput: {
    flex: 1,
    border: 'none',
    background: 'transparent',
    fontFamily: SERIF,
    fontSize: 18,
    color: C.ink,
    padding: '8px 0',
    outline: 'none',
  },
  cardFoot: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 22,
    paddingTop: 18,
    borderTop: `1px solid ${C.border}`,
  },
  count: {
    fontFamily: SANS,
    fontSize: 12,
    color: C.inkFaint,
    letterSpacing: '0.04em',
  },
  btn: {
    background: C.ink,
    color: '#fff',
    border: 'none',
    borderRadius: 3,
    padding: '10px 22px',
    fontFamily: SANS,
    fontSize: 13,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    fontWeight: 500,
    cursor: 'pointer',
  },
  btnGhost: {
    background: 'transparent',
    color: C.ink,
    border: `1px solid ${C.ink}`,
    borderRadius: 3,
    padding: '9px 18px',
    fontFamily: SANS,
    fontSize: 12,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    cursor: 'pointer',
  },
  sideStack: { display: 'flex', flexDirection: 'column', gap: 24 },
  dot: (color) => ({
    display: 'inline-block',
    width: 9, height: 9,
    borderRadius: '50%',
    background: color,
    marginRight: 10,
    transform: 'translateY(-1px)',
  }),
  verdictTitle: {
    fontFamily: SERIF,
    fontSize: 28,
    lineHeight: 1.15,
    letterSpacing: '-0.015em',
    margin: '4px 0 18px',
    display: 'flex',
    alignItems: 'center',
  },
  metaRow: {
    display: 'flex',
    justifyContent: 'space-between',
    fontFamily: SANS,
    fontSize: 11,
    color: C.inkFaint,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  barTrack: {
    height: 4,
    background: '#EEEAE0',
    position: 'relative',
    marginBottom: 20,
  },
  source: {
    display: 'grid',
    gridTemplateColumns: '20px 1fr auto',
    gap: 14,
    padding: '14px 0',
    borderTop: `1px solid ${C.border}`,
    alignItems: 'start',
  },
  sourceName: {
    fontFamily: SERIF,
    fontSize: 16,
    color: C.ink,
    marginBottom: 4,
  },
  sourceSnippet: {
    fontFamily: SERIF,
    fontSize: 14,
    color: C.inkMute,
    lineHeight: 1.5,
  },
  sourceLabel: (color) => ({
    fontFamily: SANS,
    fontSize: 10,
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    color: color,
    whiteSpace: 'nowrap',
    paddingTop: 2,
  }),
  placeholder: {
    fontFamily: SERIF,
    fontStyle: 'italic',
    color: C.inkFaint,
    fontSize: 16,
    lineHeight: 1.6,
  },
  signalRow: {
    display: 'grid',
    gridTemplateColumns: '1fr auto auto',
    alignItems: 'baseline',
    padding: '16px 24px',
    borderTop: `1px solid ${C.border}`,
    gap: 16,
  },
  signalName: {
    fontFamily: SANS,
    fontSize: 13,
    color: C.ink,
    letterSpacing: '0.02em',
  },
  signalDetail: {
    fontFamily: SANS,
    fontSize: 12,
    color: C.inkFaint,
  },
  signalValue: (color) => ({
    fontFamily: SANS,
    fontSize: 13,
    fontWeight: 600,
    color,
    letterSpacing: '0.04em',
    textAlign: 'right',
    minWidth: 110,
  }),
};

export const tdLabel = {
  fontFamily: SANS,
  fontSize: 11,
  letterSpacing: '0.12em',
  textTransform: 'uppercase',
  color: C.inkFaint,
  padding: '8px 24px 8px 0',
  borderBottom: `1px solid ${C.border}`,
  width: 160,
  verticalAlign: 'top',
};

export const tdValue = {
  fontFamily: SERIF,
  fontSize: 15,
  color: C.ink,
  padding: '8px 0',
  borderBottom: `1px solid ${C.border}`,
};
